FROM quay.io/jupyter/pytorch-notebook:latest

USER root

WORKDIR /work

RUN python -m pip install --no-cache-dir --upgrade pip \
  && python -m pip install --no-cache-dir \
    litdata==0.2.60

CMD ["python", "-c", "print('litdata optimize image ready')"]
